version: "3.8"
services:
  # Web server with PHP installed
  www:
    container_name: www
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - mysql
    ports:
      - 80:80
    restart: always
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    volumes:
      - ../usps/:/var/www/html/usps
    networks:
      - usps_network
  # Database container    
  mysql:
    container_name: mysql8
    image: mysql:8.0.27
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=usps
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=usps
    ports:
      - 3306:3306
    networks:
      - usps_network
    volumes:
      - usps_db_volume:/var/lib/mysql
    cap_add:
      - SYS_NICE
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --default-authentication-plugin=mysql_native_password --sql_mode=""
  # PhpMyAdmin
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mysql
      - www
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql8
      - PMA_USER=usps
      - PMA_PASSWORD=password
    networks:
      - usps_network

# Name the network
networks:
  usps_network: # To preserve MySQL data we create a volume
volumes:
  usps_db_volume:
